# Generated by Django 4.2.7 on 2023-11-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_congreso', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('rol', models.CharField(max_length=20)),
            ],
        ),
    ]
