# Generated by Django 4.2.7 on 2023-11-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Congresos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='congreso',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
