# Generated by Django 4.2.7 on 2023-11-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_colaborador_publicacion_alter_integrante_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
