# Generated by Django 4.2.7 on 2023-11-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_integrante_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='ingreso',
            field=models.DateTimeField(null=True),
        ),
    ]
