# Generated by Django 4.2.7 on 2023-11-18 20:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_integrante_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='biografia',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='area_investigacion',
            field=models.CharField(max_length=50),
        ),
    ]
